services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1unbelivablePASSWORD1
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - UPLOADTHING_TOKEN=eyJhcGlLZXkiOiJza19saXZlXzJkNjRhZmFlOTY0YTQ0NDI2MGQ5N2Y5ZDkwZTUzYmQ2OTgyNDk2MGE5MzlhZTMyMzY5ZDk3OTI1MmQ3NjYzZWMiLCJhcHBJZCI6IjI3djJlNTgyZGoiLCJyZWdpb25zIjpbInNlYTEiXX0=
      - UPLOADTHING_APP_ID=27v2e582dj
      - DATABASE_URL=postgresql://postgres:1unbelivablePASSWORD1@db:5432/myapp?schema=public
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "rm -rf .next &&
             sleep 10 &&
             bunx prisma generate &&
             bunx prisma migrate deploy &&
             bun run dev"

volumes:
  postgres_data: